### ISSUE TITLE
Rename Presto references to TrinoDB

### ISSUE THREAD

**Issue by Lewuathe** [treasure-data/trino-client-ruby#64]
The community decided to [rename PrestoSQL to TrinoDB](https://trino.io/blog/2020/12/27/announcing-trino.html). Although we can keep using presto-client-ruby for both [TrinoDB](https://trino.io/) and [PrestoDB](https://prestodb.io/) as long as the protocol is compatible, we should make the primary support explicit by renaming Presto references to Trino as the Trino community does.

**Comment by xerial** [comment]
Unfortunately, the protocol is incompatible because Trino uses X-Trino-XXX headers instead of X-Presto-XXX HTTP headers. Before a compatibility layer is deployed on our production (which is planned in Jan 2021), if we make this change, we will end up losing the capability of any bug fixes and feature addition.

For the actual transition work of this ruby client, we need to change the module name (from prestoxxx to trinoxxx) and these HTTP header names. If we need to support both Presto and Trino, checking `/v1/info` version and if it is 351 or higher, switch the HTTP header prefix to use. Or we can add an option to the class constructor to support Presto as a legacy protocol.

**Comment by marcotc** [comment]
>  Before a compatibility layer is deployed on our production (which is planned in Jan 2021), if we make this change, we will end up losing the capability of any bug fixes and feature addition.

@xerial, is there progress on the mentioned work for a compatibility layer?
I'm looking forward to upgrading my `starburstdata/presto` images to trino ones, but can't risk breaking compatibility with older presto clients that are already deployed.

**Comment by yuokada** [comment]
@marcotc cc: @xerial They talked about changes for their internal products. As far as I know, @xerial  has no plan to publish it as OSS.

**Comment by xerial** [comment]
I think we can close this issue as the reference has been changed to Trin. Regarding the compatibility layer between Presto and Trino, I don't think there are so many users who need this (Presto users can still use the old version of this client).
